### ISSUE TITLE
traci.exceptions.TraCIException: Invalid route 'platoon_route' for vehicle 'v.0'.

### ISSUE THREAD

**Issue by lcipolina** [michele-segata/plexe-pyapi#5]
Hello Michele,
I apologize for having so many questions. It seems that something got broken between my installation of PLEXE-VEINS and this PlexeAPI. My sense is that the error comes from the SUMO side, but I can't tell for sure, since SUMO seems to work. 

I am able to run the PLEXE-VEINS example, on SUMO 1.6 (built from source). See screenshot below. 

But when I try to use the API, I get the following messages:

(plexe) alpha@alpha:~/src/plexe-pyapi/examples$ python joindemo.py
```
 Retrying in 1 seconds
Loading configuration ... done.
Traceback (most recent call last):
  File "joindemo.py", line 217, in <module>
    main(True, False)
  File "joindemo.py", line 176, in main
    topology = add_vehicles(plexe, N_VEHICLES, real_engine)
  File "joindemo.py", line 75, in add_vehicles
    50, 0, SPEED, DISTANCE, real_engine)
  File "/home/alpha/src/plexe-pyapi/examples/utils.py", line 83, in add_platooning_vehicle
    add_vehicle(plexe, vid, position, lane, speed, vtype)
  File "/home/alpha/src/plexe-pyapi/examples/utils.py", line 64, in add_vehicle
    typeID=vtype)
  File "/usr/share/sumo/tools/traci/_vehicle.py", line 1444, in add
    arrivalLane, arrivalPos, arrivalSpeed, fromTaz, toTaz, line, personCapacity, personNumber)
  File "/usr/share/sumo/tools/traci/domain.py", line 184, in _setCmd
    self._connection._sendCmd(self._cmdSetID, varID, objectID, format, *values)
  File "/usr/share/sumo/tools/traci/connection.py", line 178, in _sendCmd
    return self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 95, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Invalid route 'platoon_route' for vehicle 'v.0'.
```
And the SUMO log:
```
Loading configuration ... done.
***Starting server on port 41585 ***
Loading net-file from 'cfg/freeway.net.xml' ... done (21ms).
Loading done.
Error: attribute 'departSpeed' is not declared for element 'vType'
 In file 'cfg/freeway.rou.xml'
 At line/column 11/29.

Quitting (on error).
Simulation started with time: 0.00
Error: Answered with error to command 0xc4: Invalid route 'platoon_route' for vehicle 'v.0'.
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
```

I have re installed this plexe-pyapi whith no luck. This library was working before I've compiled the PLEXE-VEINS one. Here is a screenshot of the plexe-veins library where you can see it running and the SUMO version on top.

![image](https://user-images.githubusercontent.com/5190890/90796088-dc01a800-e2dc-11ea-920b-5cc4ddcd4434.png)

The following is my SUMO information. I had to build it from source since installing the package 'osgearth'   (and OpenSceneGraph) broke my vanilla installation.
```
(plexe) alpha@alpha:~/src/plexe-pyapi/examples$ sumo --version
Eclipse SUMO sumo Version v1_6_0+1506-2afc834eec
 Build features: Linux-5.3.0-62-generic x86_64 GNU 7.5.0 Release Proj GUI SWIG GDAL GL2PS
```

**Comment by michele-segata** [comment]
Are you using the standard example or did you make some changes? Because the route is declared inside the [freeway.rou.cfg](https://github.com/michele-segata/plexe-pyapi/blob/master/examples/cfg/freeway.rou.xml#L15) file. The same holds for the [departSpeed](https://github.com/michele-segata/plexe-pyapi/blob/master/examples/cfg/freeway.rou.xml#L9) parameter.

**Comment by michele-segata** [comment]
I'm closing this due to inactivity.
